</$objtype/mkfile

<mk.common

</sys/src/cmd/mklib

clean nuke:V:
	@{ cd test; mk $target }
	rm -f *.[$OS] [$OS].out $LIB

test:QV:
	@{
		cd test
		mk clean
		mk all
		for(t in $O.*){
			echo $t...
			./$t
		}
	}
